[package]
name = "octopustock"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.10"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tempfile = "3.10.1"
tokio = { version = "1.39.1", features = ["full"] }
yahoo_finance_api = "2.2.1"
